### ISSUE TITLE
TypeError: Cannot set property '5841760' of null at initliazeXmlForBrowser

### ISSUE THREAD

**Issue by AryanJ-NYC** [tornaia/karma-sonarqube-unit-reporter#28]
```
TypeError: Cannot set property '56021360' of null
    at initliazeXmlForBrowser (karma-sonarqube-unit-reporter/index.js:50:40)
    at SonarQubeUnitReporter.onBrowserStart (karma-sonarqube-unit-reporter/index.js:106:5)
    at Server.<anonymous> (karma/lib/events.js:40:26)
    at Server.emit (events.js:187:15)
    at Browser.onStart (karma/lib/browser.js:123:18)
    at Socket.socket.on (karma/lib/browser.js:269:39)
    at Socket.emit (events.js:182:13)
    at socket.io/lib/socket.js:513:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:58825) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

Versions:
```
"jasmine-core": "~3.1.0",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~2.0.5",
"karma-coverage-istanbul-reporter": "^2.0.1",
"karma-jasmine": "~1.1.2",
"karma-jasmine-html-reporter": "^0.2.2",
"karma-phantomjs-launcher": "^1.0.4",
"karma-sonarqube-unit-reporter": "0.0.17",
```

Bug reproduced when saving a spec file while tests are running.

Similar junit bugs:
karma-runner/karma-junit-reporter#20
https://github.com/karma-runner/karma-junit-reporter/issues/61

**Comment by llehn** [comment]
We have same problem. Weird thing is, it used to work, and this error started showing up without any relevant package.json changes

**Comment by llehn** [comment]
We changed tests to run in Chrome instead of ChromeHeadless and the issue vanished.

**Comment by Manish2005** [comment]
Just wondering if there's any update on this issue?

**Comment by SanthoshBanavath** [comment]
Is there any fix or update on this?

**Comment by ghost** [comment]
As a workaround it helped to downgrade `socket.io` to `4.7.0`. 

```json
{
...
    "overrides": {
        "socket.io": "4.7.0"
    }
}
```

**Comment by tornaia** [comment]
Fixed in 1.0.0 (#75). The reporter no longer reads the XML back while collecting results, so this crash cannot happen any more; see [CHANGELOG.md](https://github.com/tornaia/karma-sonarqube-unit-reporter/blob/master/CHANGELOG.md) for the full list of changes. Please reopen if you still hit it with 1.0.0.
