### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by sebastianteres** [tornaia/karma-sonarqube-unit-reporter#72]
This is the same issue described in #53
Some of us are still having this problem and it's not clear how to resolve.

```sh
12 04 2023 18:05:53.669:ERROR [karma-server]: UncaughtException: TypeError: Cannot read property 'children' of undefined
    at SonarQubeUnitReporter.specSuccess.specSkipped.specFailure (C:\agent\_work\7\s\node_modules\karma-sonarqube-unit-reporter\index.js:152:39)
    at SonarQubeUnitReporter.BaseReporter.onSpecComplete (C:\agent\_work\7\s\node_modules\karma\lib\reporters\base.js:107:12)
    at Server.<anonymous> (C:\agent\_work\7\s\node_modules\karma\lib\events.js:40:26)
    at Server.emit (events.js:327:22)
    at Browser.onResult (C:\agent\_work\7\s\node_modules\karma\lib\browser.js:164:20)
    at Socket.<anonymous> (C:\agent\_work\7\s\node_modules\karma\lib\browser.js:218:42)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (C:\agent\_work\7\s\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\agent\_work\7\s\node_modules\socket.io\dist\socket.js:466:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by jignesh3094** [comment]
What is the solution for this error

**Comment by sebastianteres** [comment]
I ended up replacing karma-sonarqube-unit-reporter with [karma-sonarqube-reporter](https://github.com/fadc80/karma-sonarqube-reporter)

**Comment by jignesh3094** [comment]
With karma-sonarqube-unit-reporter  In local it is working fine but in jenkins only creating issue

**Comment by jignesh3094** [comment]
Working fine with karma-sonarqube-reporter
Thank you

**Comment by hlovdal** [comment]
@jignesh3094 I think this is related to node.js version, so try to downgrade and see if that works.

**Comment by tornaia** [comment]
Fixed in 1.0.0 (#75). The reporter no longer reads the XML back while collecting results, so this crash cannot happen any more; see [CHANGELOG.md](https://github.com/tornaia/karma-sonarqube-unit-reporter/blob/master/CHANGELOG.md) for the full list of changes. Please reopen if you still hit it with 1.0.0.
